// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAePuOY6s4MGZyTgftuMTniFwKVcmmT59E',
    appId: '1:1037952992835:web:aca77d470810abc1acf6f6',
    messagingSenderId: '1037952992835',
    projectId: 'aibuddy-app',
    authDomain: 'aibuddy-app.firebaseapp.com',
    storageBucket: 'aibuddy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYT9bwiciSHkxlY2C9T50HeI4v5R32QU',
    appId: '1:1037952992835:android:fef5148a5db85a45acf6f6',
    messagingSenderId: '1037952992835',
    projectId: 'aibuddy-app',
    storageBucket: 'aibuddy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWM24SHhwAmenDNcrXyw7Keg_FPkl78Q',
    appId: '1:1037952992835:ios:573d52a6cdb14328acf6f6',
    messagingSenderId: '1037952992835',
    projectId: 'aibuddy-app',
    storageBucket: 'aibuddy-app.firebasestorage.app',
    androidClientId: '1037952992835-5ismp11v2d7989tg327menq73sqcf948.apps.googleusercontent.com',
    iosClientId: '1037952992835-1qec792ffsmn6url9gqld9pjb81nm9mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aibuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsWM24SHhwAmenDNcrXyw7Keg_FPkl78Q',
    appId: '1:1037952992835:ios:573d52a6cdb14328acf6f6',
    messagingSenderId: '1037952992835',
    projectId: 'aibuddy-app',
    storageBucket: 'aibuddy-app.firebasestorage.app',
    androidClientId: '1037952992835-5ismp11v2d7989tg327menq73sqcf948.apps.googleusercontent.com',
    iosClientId: '1037952992835-1qec792ffsmn6url9gqld9pjb81nm9mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.aibuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAePuOY6s4MGZyTgftuMTniFwKVcmmT59E',
    appId: '1:1037952992835:web:08afe4c3663df204acf6f6',
    messagingSenderId: '1037952992835',
    projectId: 'aibuddy-app',
    authDomain: 'aibuddy-app.firebaseapp.com',
    storageBucket: 'aibuddy-app.firebasestorage.app',
  );

}